### ISSUE TITLE
update from 1.1.0 to 4.1.3 - webhook no longer sends all info

### ISSUE THREAD

**Issue by 007mcfod** [mageplaza/magento-2-webhook#107]
we've been using 1.1.0 successfully for a couple years, this week we updated to see if one of the changelog items in 4.1.3 would help with some other functionality (which it doesnt) - but worse than that, the old webhooks are now having problems

I've checked the main problematic webhook for any changes and no difference, I've referenced it back against a backup and all attributes are identical, but when it sends the shipping address for the order it isnt actually including any data, you can see on this screengrab the old one includes name, address info, etc, the new hook (not actually a new hook, just a new order placed after we updated) has none of this info included

anyone seen anything similar?? any ideas or thoughts

![image](https://user-images.githubusercontent.com/121239321/209176018-0795007d-5579-48e9-bba0-5333d362b2f1.png)

**Comment by KhietNguyen83** [comment]
Regarding this issue, please download the extension directly from our site https://www.mageplaza.com/magento-2-webhook/ along with the support package for further inspections and technical support. Thanks a lot!

**Comment by 007mcfod** [comment]
> Regarding this issue, please download the extension directly from our site https://www.mageplaza.com/magento-2-webhook/ along with the support package for further inspections and technical support. Thanks a lot!

thanks, but hoping for some community help here, a simple update with no change in the hook seetings should be a straightforward process - if their was levels of complexity added to the extension that we were struggling with i would happily pay but this should be straighforward enough

**Comment by 007mcfod** [comment]
should anyone else come across this issue - I've resolved it - the update went well and the webhook carried across, however what isnt detailed anywhere in the user manual or any changelogs is that the actual content of each variable has been changed, as an example, {{ shipping.prefix }} becomes {{ item.shippingAddress.prefix }} - I should have spotted this sooner, but hopefully this helps someone - all I did was go into each line of the hook, delete the old variable code and replace with the new version and a test of the action that triggers the hook worked
