### ISSUE TITLE
Webhook not firing on ver. 2.3.2

### ISSUE THREAD

**Issue by znikolovski** [mageplaza/magento-2-webhook#12]
Magento version: Community edition 2.3.2
PHP: 7.2.20
MySQL: 5.7.26

Webhook configuration:
Update Product:
 - Method: POST
 - No Authentication
 - Content Type: application/json
 - Body: {"test": "test")

Expected behaviour: When updating a product a webhook event is fired. Log entry is recorded

Current behaviour: When updating a product no webhook events are recorded at endpoint and no log entries are created.

<img width="988" alt="Screen Shot 2019-08-14 at 9 34 34 am" src="https://user-images.githubusercontent.com/9601579/62985450-b268a200-be7a-11e9-9493-0eaec2d3baf4.png">

**Comment by NgoDuVietHung97** [comment]
Hi @znikolovski,

To solve this problem, please download and replace the attached file:
 - AfterSave.php: Mageplaza/Webhook/Observer/AfterSave.php

[AfterSave.zip](https://github.com/mageplaza/magento-2-webhook/files/3500930/AfterSave.zip)

Then, please clear the cache and try it again.
Thank you!

**Comment by znikolovski** [comment]
Hi @NgoDuVietHung97 - thanks for the reply!

I'll post back with results once I've had a chance to test this.

**Comment by peterjaap** [comment]
I tested it on 2.3.3, does not work. Nothing in the logs.

**Comment by sipy** [comment]
Hello I tested it on 2.3.3 (with PHP 7.2), does not work, too. There is no log. Any suggestion?

Thanks

**Comment by sipy** [comment]
@NgoDuVietHung97 your fix works for the Subscriber Observer, too. I think it is an issue present in all Observers that has the buggy if statement.

Thanks!

**Comment by Bang512** [comment]
Hi,

Sorry for the delay. Did the problem has been solved?
Please don't hesitate to let me know if you have any questions or problems with our extension.
Thanks!

**Comment by edsonnieto** [comment]
Thanks a lot!!! it's work for me;  nevertheless a couple of things to finish solve issue, you must clean cache and compile again bin/magento setup:di:compile.
