### ISSUE TITLE
Unable to install package through composer 

### ISSUE THREAD

**Issue by Spartaa** [mageplaza/magento-2-webhook#14]
Installation failed, reverting ./composer.json to its original content.

                                                                                                                                                                                 
  [Composer\Downloader\TransportException]                                                                                                                                       
  The "https://packagist.org/p/symfony/stopwatch%24dfe4272304cce72b7d6a4fdf123fbf5588270a64578a4200b49293d7d527bc5e.json" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by NgoDuVietHung97** [comment]
Hi @Spartaa,

I'm not sure I can understand your problem.
So could you please explain your problem step by step then I can understand your problem and give you the best solution.

I am looking forward to hearing from you.
Thanks!

**Comment by Spartaa** [comment]
@NgoDuVietHung97  I was trying to install webhooks in my magento project at local host 
but when ever i run this 
composer require mageplaza/module-webhook

 after some time it gives me an error

Using version ^1.1 for mageplaza/module-webhook
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, reverting ./composer.json to its original content.

                                                                                                                                                                                 
  [Composer\Downloader\TransportException]                                                                                                                                       
  The "https://packagist.org/p/symfony/stopwatch%24dfe4272304cce72b7d6a4fdf123fbf5588270a64578a4200b49293d7d527bc5e.json" file could not be downloaded (HTTP/1.1 404 Not Found)  
                                                                                                                                                                                 

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-r
eqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
