### ISSUE TITLE
Not registered handle mageplaza_webhook_hook_listing_data_source

### ISSUE THREAD

**Issue by SzabKel** [mageplaza/magento-2-webhook#17]
Using Magento `2.3.3` I am receiving an error instead of the listing for the hooks.:
![magento-webhook-handle-233](https://user-images.githubusercontent.com/3736434/66815400-744e3400-ef38-11e9-8769-14df3efaec00.png)

`Not registered handle mageplaza_webhook_hook_listing_data_source`

I could add a hook without an error, but the listing still does not work.

Environment: 
Bitnami VM https://bitnami.com/stack/magento for 2.3.3

No other module is installed.

I installed the module using:
```
composer require mageplaza/module-webhook
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
```
I had no errors during these.

**Comment by SzabKel** [comment]
After running there (again), the problem solved:
```
php bin/magento setup:upgrade
php bin/magento module:enable Mageplaza_Webhook
php bin/magento setup:static-content:deploy
php bin/magento cache:flush
```

**Comment by janpjens** [comment]
Worked for me too - thanks @SzabKel !
