### ISSUE TITLE
Hooks not firing

### ISSUE THREAD

**Issue by gioamato** [mageplaza/magento-2-webhook#18]
Hi there,

is this module still working?
I was trying it on a vanilla magento deployment (v2.3.3).
Added POST and GET hooks on `new_order` and `new_customer` but they are not firing.
No logs at all and no events at the API endpoint.

**Comment by Bang512** [comment]
Hi @gioamato,

Sorry for the late response.
I have tested our module on the local environment (Magento-v2.3.3) and it seems everything still works well.

Please make sure you fill in the basic information of the hook correctly.
Thanks!

**Comment by Bang512** [comment]
Hi @gioamato,

Sorry for the late response.
I have tested our module on the local environment (Magento-v2.3.3) and it seems everything still works well.

Please make sure you fill in the basic information of the hook correctly.
Thanks!

**Comment by gioamato** [comment]
Could you give me your tested hook configuration?

**Comment by Bang512** [comment]
Hi @gioamato,

I have created a new hook "New Customer GET" and get data from `https://www.mockapi.io`.
Here is my information: 
http://prntscr.com/pmzg06
http://prntscr.com/pmzg7c
and here is the result: http://prntscr.com/pmzgjb, http://prntscr.com/pmzgvd
 - payload url: `https://5daecb6bf2946f001481ce0c.mockapi.io/api/mp/test/user`
 - Method: GET
 - Content Type: application/json

**Comment by gioamato** [comment]
Intereting. I've used your configuration, but still nothing. Should the hook fire if a create a new customer in the admin area? Or will it works only for customer creation from the frontend?

**Comment by Bang512** [comment]
Hi @gioamato,

I have tried to create a new customer in the admin area and I still get data from fakeAPI.
Seem everything still works normally.

**Comment by gioamato** [comment]
Thank you @Bang512,

so i guess i'm missing something. Does the extension need any dependency?
I've just used `composer require mageplaza/module-webhook`, am i missing something?

**Comment by Bang512** [comment]
Hi @gioamato,

Our extension depends on the Liquid library.
You can install Liquid library by the composer:
Please use `composer require liquid/liquid` in your Magento installation folder

Thanks!

**Comment by gioamato** [comment]
Allright, sorry. Just found it in the docs. I'm going to install Liquid.

Just another question: on `new_order` how can i export in the body all the order's rows (product sku, quantity, price, etc.)?

**Comment by Bang512** [comment]
Hi @gioamato,

You can find all order's information by click "Insert Variable": 
http://prntscr.com/pmzzlg
You can insert every variable with information as you want here.

**Comment by gioamato** [comment]
Yes, i'm looking at Variables. Haven't you an example about iterating and exporting order's rows?
