### ISSUE TITLE
Webhook for customer newsletter subscription

### ISSUE THREAD

**Issue by sipy** [mageplaza/magento-2-webhook#19]
Hello,
is there a webhook I can use to trigger when a customer subscribes to the newsletter? If not it would be nice to have in order to be able to integrate this action with some CRMs like Agile CRM for example.

Thank you!

**Comment by Shinichi69** [comment]
Hi @sipy 

I’m Shin from Mageplaza.com and I will support you on this issue.

For your question, you can create a new hook with the 'subscriber' option.
Please see this screenshot:
- http://prntscr.com/q93g80

Thanks so much!

**Comment by sipy** [comment]
Thank you very much!

**Comment by sipy** [comment]
Hello I tested it (Subscriber Webhook) on 2.3.3 (with PHP 7.2), does not work, too. There is no log. Any suggestion?

Thanks

**Comment by sipy** [comment]
Found the fix here: https://github.com/mageplaza/magento-2-webhook/issues/12#issuecomment-521190268
