### ISSUE TITLE
Webhook with multi-vendor data

### ISSUE THREAD

**Issue by eglimi** [mageplaza/magento-2-webhook#21]
Hi, we use Magento (version 2.3.3) with a multi-vendor plugin from Webkul. For new orders, we would like to notify an external service. This webhook plugin would be perfect for this. However, the problem is that not all data that we require is available. Namely, for a new order, we would need the shipper address (the origin of a shipment) and the receiver address (the destination of a shipment).

Would it be feasible, and would you be interested in adding this to the webhook plugin, or is it better to create a custom implementation for this?

Thank you!

**Comment by Shinichi69** [comment]
Hi @eglimi,

About get the receiver address information, we can customize it to help you get the address of the recipient.
However, we need to know exactly the recipient information you want to get.
Please send me screenshot of that information in a specific order.

About get the shipper address, I’m not sure that I can understand your issue/question.
So could you please explain your problem in more details/ steps by steps to replicate the problem and send me some screenshots?

I really hope for your cooperation. 
Thank you!

**Comment by eglimi** [comment]
Hi, thanks for your feedback.

I try to explain the problem. Magento, without any multi-vendor plugins, is a regular web shop. If a person orders something from the shop, there are the following participants.

- The customer (the person who orders a product)
- The seller (the person / company which runs the webshop and sells the product)

In this case, shipment works as follows. Let's assume we ship through USPS.

- The seller has an account with USPS
- USPS picks up a parcel at the sellers address
- USPS ships it to the customer

I believe this workflow works fine with the webhook plugin. However, with a multi-vendor plugin, it becomes different. There are the following participants.

- The customer (the person who orders a product)
- The producer (the person / company which produces and ships the product)
- The webshop owner (the person / company which runs the webshop)

As you can see, the seller is now split into two separate entities (producer and webshop owner). For shipping, this changes the workflow.

- The webshop owner has an account with USPS
- USPS picks up a parcel at the producer's address (note, not at the webshop owners address)
- USPS ships it to the customer

As far as I can see, it is only possible to get the address of the customer and the webshop owner. I don't see a way to the get the address of the producer in the second use case (multi-vendor). This address however is necessary for USPS to know where to pick-up a parcel.

Let me know if this explanation is clear. Again, I'm not sure if it is reasonable to change the webhook plugin in such a way that this address is accessible. I assume it would thigh the plugin to the specific multi-vendor plugin.

**Comment by Shinichi69** [comment]
Hi @eglimi 

Thanks for your response.

I have understood your request.

Unfortunately, the current version has not supported this function yet. I'm so sorry about that. However, If the producer's address information is added to your order, I can check your website to see if we can get these values.

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
