### ISSUE TITLE
New order custom product attribute

### ISSUE THREAD

**Issue by 0stone0** [mageplaza/magento-2-webhook#22]
None of the listed variables at `Manage Hooks -> Add new -> New Order -> Actions -> Insert Variables` provide enough information about the ordered products for us to properly handle new orders. 

Is it possible to somehow add a custom product attribute for each product ordered to the `New Order` webhook? 

eg;
### new_order body
```
subarticlenumber |      qty    
----------------------------
34567890         |       2
HL58AGK9         |       1
HBA48FJAFG       |       3

{{ item.status }}, {{ item.base_subtotal }}, ..., ....
```

**Comment by Shinichi69** [comment]
Hi @0stone0 

I’m Shin from Mageplaza.com and I will support you on this issue.

You can add the following code to the Body to get information about the products in the order.
{% for product in item.items %}
{{ product.name }}
{{ product.sku }}
{% endfor %}

- http://prntscr.com/qibc2c

If you have any questions, please contact me via this issue.
Thank you!

**Comment by 0stone0** [comment]
Hi @Shinichi69,

Many thanks! This solves our product problem.

Unfortunately we're still having troubles collecting some required data about the customer. 
I'm currently using the Magento 2 REST api to collect the missing data. I'd rather just use the module.

Is there an overview available with all the possible options? 
Any idea why (e.g.) `{{ item.items }}` isn't listed in the `Insert Variable` list ?

Missing fields;
```
Field            |      new_order
--------------------------------------------------------------------------------------
entity_id        |         ✓        {{ entity_id }}       
name             |         ✓        {{ customer_firstname }} {{ customer_lastname }}
street           |         ?
house_nr         |         ?
house_nr_ext     |         ?
postalcode       |         ?
city             |         ?
country          |         ?
extra_email      |         ✓        {{ customer_email }}
product_sartn    |         ✓        {% for product in item.items %}
```

**Comment by Shinichi69** [comment]
Hi @0stone0 

Unfortunately, the current version does not yet support enumeration of {{item.items}} variables.
I am very sorry about that.

However, we can customize to add the attributes you need to into the list variables and missing fields
and you will be charged a fee to perform this customization.

If you want, you can submit your ticket here:
- https://www.mageplaza.com/contact.html

Thanks so much!

**Comment by 0stone0** [comment]
Hi @Shinichi69,

Thank you for the information! I'll request a ticket is i'm not able to fulfill the missing information with the REST api. 

Many thanks!

Stijn
