### ISSUE TITLE
Sending web-hook JSON data for new order

### ISSUE THREAD

**Issue by somunelavalli** [mageplaza/magento-2-webhook#24]
Hi Shin,
I heed your help
i have created a new hook it will send the message to slack when new order come but here i am facing one problem
in cart if i had 1 product we are getting message in slack
but if you add more than one product we are not getting message in slack.
Below is the code in Body
{
{% for product in item.items %}
"text": "You Have Got a New Order From Vitalticks.in
Purchase Date:{{ item.created_at }}
Order Number :{{ item.increment_id }}
Product Name :{{ product.name}}
SKU :{{ product.sku }}
Quantity :{{ item.total_qty_ordered }}
Customer Name:{{ item.customer_firstname }}
Delivery Address:{{ item.billingAddress.street | strip_newlines }}
Phone Number :{{ item.billingAddress.telephone }}
Cart Value :{{ item.base_grand_total }}
"
{% endfor %}
}

**Comment by Shinichi69** [comment]
Hi @somunelavalli 

I have checked your problem.
Please change your body as follows and try again.

{
	{% for product in item.items %}
    "text": "You Have Got a New Order From Vitalticks.in
   	 Purchase Date:{{ item.created_at }}
	 Order Number :{{ item.increment_id }}
	 Product Name :{{ product.name}}
  	 SKU		   :{{ product.sku }}
	 Quantity     :{{ item.total_qty_ordered }}
	 Customer Name:{{ item.customer_firstname }}
	 Delivery Address:{{ item.billingAddress.street | strip_newlines }}
	 Phone Number :{{ item.billingAddress.telephone }}
	 Cart Value   :{{ item.base_grand_total }}
"{% if forloop.last != true %},{% endif %}
	{% endfor %}
}

Thank you!

**Comment by somunelavalli** [comment]
Hi Shin,

We are getiing Now.

But if we place two items it is coming two times with same Product name.

For Reference Plaese FInd the attached URL
https://prnt.sc/qmue96

**Comment by Shinichi69** [comment]
Hi @somunelavalli 

I tried a new order with 2 items and I received 2 different product names in the webhook.log file
Please see this screenshot:
- https://prnt.sc/qnb32a

Please check again.
Thank you!

**Comment by somunelavalli** [comment]
But in slack we are not getting like this

**Comment by Shinichi69** [comment]
Hi @somunelavalli 

Please let me know if you are checking for issues on the dev site you sent me before, or are you checking on your live site?

If you are checking on the live site, please download and replace the Data.php file from dev site to live site follow the path:
- /home/vitalticks/public_html/dev/vendor/mageplaza/module-webhook/Helper/Data.php

Then, please check again and let me know the result.

Thank you!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
