### ISSUE TITLE
Hooks firing twice after the last update on ver 2.3.2

### ISSUE THREAD

**Issue by AboElnoor** [mageplaza/magento-2-webhook#26]
Hi,
I'm installing this extension on Magento 2 using the composer and I'm creating a Slack webhook.
and since 10 days after running `composer update` the slack webhook firing twice so I get duplicate message on each new order.

**Comment by Shinichi69** [comment]
Hi @AboElnoor,

To solve your problem, please download and replace this file follow the path:

- <Magento_root>/vendor/mageplaza/module-webhook/Helper/Data.php

Then please clear all the cache and let me know the result.

Thanks so much!
[Data.zip](https://github.com/mageplaza/magento-2-webhook/files/4372700/Data.zip)

**Comment by AboElnoor** [comment]
I did it and cleared the cache, but the issue didn't work.


> Hi @AboElnoor,
> 
> To solve your problem, please download and replace this file follow the path:
> 
> * <Magento_root>/vendor/mageplaza/module-webhook/Helper/Data.php
> 
> Then please clear all the cache and let me know the result.
> 
> Thanks so much!
> [Data.zip](https://github.com/mageplaza/magento-2-webhook/files/4372700/Data.zip)

**Comment by Shinichi69** [comment]
Hi @AboElnoor

Could you create a ticket here and provide me with your SSH and admin information so I can check your issue directly?
- https://mageplaza.freshdesk.com/support/tickets/new

Thanks so much!

**Comment by Shinichi69** [comment]
Hi @AboElnoor 

Please check your issue at the ticket you created, I will continue to support you at that ticket.

Thanks so much!
