### ISSUE TITLE
Skip Webhook when Service URL is down

### ISSUE THREAD

**Issue by diyontheweb** [mageplaza/magento-2-webhook#27]
Hi guys,

Is it possible to have webhook be skipped if the web hook URL is not accessible.

Today we had a power outage at our webhook service URL, which meant when a new customer registers on the store - the webhook fails with error 'Cannot connect to server. Please try again later.'

This then holds blocks the customer from being created in the database for 3 minutes. Which causes nginx to time out.

When the webhook URL is down it should not block customer creation or order creation waiting for a timeout.

Thanks

**Comment by thaimageplaza** [comment]
Hi,
I cannot reproduce your issue on my site.
But, You can try replacing the attachment below.
It will limit the wait time when the connection is 10s
These are modified files:
Mageplaza/Webhook/Helper/Data.php
[Data.zip](https://github.com/mageplaza/magento-2-webhook/files/4592451/Data.zip)

**Comment by diyontheweb** [comment]
Thanks for your reply.

I am trying to avoid any customisation to files as it will be overridden by a composer update. Do you think enabling cron to 1 minute will alleviate this as technically if its run as a cron job it shouldn't block the customer from being created.

Which brings up a good point as I'm currently unable to save any new web hooks as the changes made to the Save.php file previously have been erased by this. We're currently on single store mode.

I'm not sure if this was ever updated in this repo: https://github.com/mageplaza/magento-2-webhook/issues/5

Exception #0 (Exception): Warning: implode(): Invalid arguments passed in /mnt/data/home/108422.cloudwaysapps.com/ndcfdqpqmj/public_html/vendor/mageplaza/module-webhook/Controller/Adminhtml/ManageHooks/Save.php on line 82

        if (isset($data['store_ids']) && $data['store_ids']) {
            $data['store_ids'] = implode(',', $data['store_ids']);
        }

Thanks

**Comment by peterjaap** [comment]
Here's a patch to use with `vaimo/composer-packages`;

```
Fix store_ids in single store mode

@link https://github.com/mageplaza/magento-2-webhook/issues/5
@package mageplaza/module-webhook
@level 0


diff --git Controller/Adminhtml/ManageHooks/Save.php Controller/Adminhtml/ManageHooks/Save.php
index e5efe65..209fa3b 100755
--- Controller/Adminhtml/ManageHooks/Save.php
+++ Controller/Adminhtml/ManageHooks/Save.php
@@ -83,7 +83,7 @@ class Save extends AbstractManageHooks
         }
 
         if (isset($data['store_ids']) && $data['store_ids']) {
-            $data['store_ids'] = implode(',', $data['store_ids']);
+            $data['store_ids'] = is_array($data['store_ids'])?implode(',', $data['store_ids']):$data['store_ids'];
         }
 
         $hook->addData($data);

```
