### ISSUE TITLE
Error getting billing_address

### ISSUE THREAD

**Issue by icychocolate98** [mageplaza/magento-2-webhook#29]
Hi,

I'm trying to get billing_address information like this:

"billing_address_info":{
"parent_id":"{{ item.billing_address.parent_id}}",
"address_type":"{{ item.billing_address.address_type}}",
"region":"{{ item.billing_address.region}}",
"region_code":"{{ item.billing_address.region_code}}",
"region_id":"{{ item.billing_address.region_id}}",
"email":"{{item.billing_address.email }}",
"firstname":"{{ item.billing_address.firstname}}",
"lastname":"{{ item.billing_address.lastname}}",
"telephone":"{{ item.billing_address.telephone}}"
},

I expect to receive data from billing_address (in Postman I can see it using API rest endpoints).

But I receive " " in each field, do you have any idea? I don't know exactly how to map with "order" interface.

I tried to use billingAddress but it doesn't work for me,

What I found and it's quite weird is that for example if I modify AfterOrder.php file in

    "/var/www/html/vendor/mageplaza/module-webhook/Observer/AfterOrder.php"

and I do this, to get postcode in an external log file, for example:
error_log((string)$item->getBillingAddress()->getData("postcode"),3,"logFile" )

I receive correct billing_address postcode in mi logFile:

Moreover I'm trying in Magento Webhook something like this:
{{ item.billing_address.postcode }}

and I also tried:
{{ item.billingAddress.postcode }}

But I receive blank both ways, my question is how to access this same "subproperty" for example in Magento Webhook body using liquid notation. It's quite strange that is not working and in AfterOrder.php I receive everything...

Thanks a lot!

**Comment by Shinichi69** [comment]
Hi @icychocolate98 

I’m Shin from Mageplaza and I will support you on this ticket.
I have already received your issue reports and I am sorry for that.

To solve the problem, please download and replace this file follow the path:
- Webhook/Helper/Data.php

And please use variables with the following prefix:
- item.billingAddress

Then please check again.

Thanks so much!
[Data.zip](https://github.com/mageplaza/magento-2-webhook/files/4681446/Data.zip)

**Comment by icychocolate98** [comment]
Thanks so much! It worked for me, I didn't know what exactly happened.
