### ISSUE TITLE
How can I get the product_id?

### ISSUE THREAD

**Issue by alexblumte** [mageplaza/magento-2-webhook#30]
I am creating a webhook for "New Product / Update Product". Everything goes well except that I just cant' find the `{{item.product_id}}` or `{{item.entity_id}}` variable in the "Insert Variable" dialog. So, is there any way to get these variables ? thanks !

**Comment by Shinichi69** [comment]
Hi @alexblumte 

I’m Shin from Mageplaza and I will support your issue.

To be able to get the ID of the product, please use {{item.entity_id}} in the body of your hook.
This variable is currently not included in the list of variables when you click the Insert Variables button.

If you have any questions, please contact me via this ticket.
Thank you!

**Comment by alexblumte** [comment]
Great !  Thank you .
