### ISSUE TITLE
Unused Dependency Can Sometimes Cause Circular Dependency Errors in Development

### ISSUE THREAD

**Issue by perryholden** [mageplaza/magento-2-webhook#31]
Version 1.1.1

In `\Mageplaza\Webhook\Helper\Data`, the CustomerRepository is injected, but it is never used. This can cause circular dependency errors, especially when the AddressRepository is called in a custom class.

I am going to use a composer patch to remove it, but that unused dependency should be removed from the Helper.

**Comment by Bang512** [comment]
Hi @perryholden,

Thanks for your contribution.
This is very helpful, we will update this in the next release.

We highly appreciate any ideas, suggestions, and comments like yours and consider them in our next improvement to make our products better. 

Thank you very much!
