### ISSUE TITLE
Webhook when new customer created

### ISSUE THREAD

**Issue by icychocolate98** [mageplaza/magento-2-webhook#34]
I have a doubt about catching customer addresses array on my webhook when a new customer complete his/her register in my magento.

Does anyone have any template to follow ?

I'm trying this: 

`{
		"billing":{
                   "billing_address_id":"{{item.billingAddress.customer_address_id}}",
                    "billing_street" : "{{item.billingAddress.street | strip_newlines }}",
                    "billing_firstname":"{{ item.billingAddress.firstname }}",
                    "billing_lastname": "{{ item.billingAddress.lastname }}",
                    "billing_email": "{{ item.billingAddress.email }}",
                    "billing_phone": "{{ item.billingAddress.telephone }}",
                    "billing_mobile": "{{ item.billingAddress.fax }}",
                    "billing_state": "{{ item.billingAddress.region }}"
                    "billing_city": "{{ item.billingAddress.city }}",
                    "billing_zipcode": "{{ item.billingAddress.postcode }}",
                    "billing_country": "{{ item.billingAddress.country_id }}"
               },
        "shipping":{
        	"shipping_address_id":"{{item.shippingAddress.customer_address_id}}",
        	"shipping_firstname": "{{ item.shippingAddress.firstname }}",
        	"shipping_lastname": "{{ item.shippingAddress.lastname }}",
        	"shipping_email": "{{ item.shippingAddress.email }}",
        	"shipping_phone": "{{ item.shippingAddress.telephone }}",
        	"shipping_mobile": "{{ item.shippingAddress.fax }}",
        	"shipping_state": "{{ item.shippingAddress.region }}",
        	"shipping_street": "{{ item.shippingAddress.street }}",
        	"shipping_city": "{{ item.shippingAddress.city }}",
        	"shipping_zipcode": "{{ item.shippingAddress.postcode }}",
        	"shipping_country": "{{ item.shippingAddress.country_id }}",
        	"shipping_description":"{{ item.shipping_description }}",
        	"shipping_method": "{{ item.shipping_method }}"
        }
}`

**Comment by Shinichi69** [comment]
Hi @icychocolate98 

I’m Shin from Mageplaza and I will support you on this ticket.
I have already received your issue reports and I am sorry for that.

To solve the problem, please download and replace this file follow the path:

- Webhook/Helper/Data.php

And please use variables with the following prefix:

- item.billingAddress
- item.shippingAddress
[Data.zip](https://github.com/mageplaza/magento-2-webhook/files/4867241/Data.zip)


Then please check again.

Thanks so much!

**Comment by icychocolate98** [comment]
Yes, I did that on other problem. Now I have the correct Data.php.

I can't catch addresses because it only comes via REST API  i think? But if a customer adds a new address it is supposed that it sends event on "update customer" webhook, but I receive nothing about addresses.

Do you have any idea?

**Comment by Shinichi69** [comment]
Hi @icychocolate98 

Please provide me with steps to reproduce your issue.

Thanks so much!

**Comment by icychocolate98** [comment]
1. Customer creates an account.
2. Webhook fires my new_customer webhook.
3. I want to catch in my liquid template adresses array.

But I think is not possible, because when creating new customer, no addresses are given, except via API REST ...

**Comment by Shinichi69** [comment]
Hi @icychocolate98 

Firstly, I truly apologize for the inconvenience.
Unfortunately, the current version has not supported this function yet. I'm so sorry about that. 
However, I will surely note it to our developer to consider developing it in the future so please look forward to this. 

Thank you very much for your feedback.

**Comment by icychocolate98** [comment]
Thank u!
