### ISSUE TITLE
How can i Import product to magent over API

### ISSUE THREAD

**Issue by wonderlancer** [mageplaza/magento-2-webhook#35]
Hello, is it possible to import product to Magento over Rest API?
Payload URL: https://api.elkogroup.com/v3.0/api/Catalog/Products?catalog=S3D
Method: Get
Header: Authorization Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiNDAyMDc5MkAxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQXBpIiwiZXhwIjoxNjI1NTkyNjIwLCJpc3MiOiJodHRwczovL2Vjb20uZWxrb2dyb3VwLmNvbSIsImF1ZCI6Imh0dHBzOi8vZWNvbS5lbGtvZ3JvdXAuY29tIn0.xLk2ub8jlx-8h80guViZRW_QpMFPS5k2vdqp-2YIQ60

Type: application/json

What I must ad to body?

**Comment by Shinichi69** [comment]
Hi @wonderlancer 

Please check your body structure for the variables you need to use for this Payload URL.
And then fill them in the body of the hook.

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
