### ISSUE TITLE
Loop on order's items in "new order" webhook ?

### ISSUE THREAD

**Issue by YannickBiet** [mageplaza/magento-2-webhook#37]
Hello there!
We are looking to your module. According to my Magento2 dev, there's no option to send any order's items information (loop on all order lines) to send info on the "new order" webhook ?

can you please confirm and tell me if there's a workaround or the possibility to extend the webhook function to add some elements inside the webhook ?

**Comment by Shinichi69** [comment]
Hi @YannickBiet 

We have responded to you on your ticket.
Please check it out.

Thanks so much!
