### ISSUE TITLE
latest release, version 1.1.3 breaks some api functions

### ISSUE THREAD

**Issue by oscar-parra** [mageplaza/magento-2-webhook#39]
Last release, version 1.1.3 breaks some functions of the magento api, my composer json pointed to ^1.1.1 so I was forced to return the version by forcing the composer json to 1.1.1

we did not review thoroughly but the functions it broke were login and registration through apirest in our case

magento version =  2.3.4

report show this

"Fatal Error: 'Uncaught Error: Call to undefined method Magento\\Customer\\Model\\Data\\Customer::getData() in \/var\/www\/html\/mobu\/releases\/66dc23af4c08399bfe4838aa3c0d577267dd4407\/vendor\/mageplaza\/module-webhook\/Helper\/Data.php:136\nStack trace:\n#0 \/var\/www\/html\/mobu\/releases\/66dc23af4c08399bfe4838aa3c0d577267dd4407\/vendor\/mageplaza\/module-webhook\/Helper\/Data.php(157): Mageplaza\\Webhook\\Helper\\Data->getItemStore(Object(Magento\\Customer\\Model\\Data\\Customer))\n#1 \/var\/www\/html\/mobu\/releases\/66dc23af4c08399bfe4838aa3c0d577267dd4407\/vendor\/mageplaza\/module-webhook\/Observer\/CustomerLogin.php(74): Mageplaza\\Webhook\\Helper\\Data->send(Object(Magento\\Customer\\Model\\Data\\Customer), 'customer_login')\n#2 \/var\/www\/html\/mobu\/releases\/66dc23af4c08399bfe4838aa3c0d577267dd4407\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(88): Mageplaza\\Webhook\\Observer\\CustomerLogin->execute(Object(Magento\\Framework\\Event\\Observer))\n#3 \/var\/www\/html\/mobu\/releases\/66dc23af4c08399bfe4838aa3c0d577267dd4407\/vendor\/magento\/framework\/Event\/Invoker\/InvokerD' in '\/var\/www\/html\/mobu\/releases\/66dc23af4c08399bfe4838aa3c0d577267dd4407\/vendor\/mageplaza\/module-webhook\/Helper\/Data.php' on line 136"

**Comment by Shinichi69** [comment]
Hi @oscar-parra 

I checked your problem on my local and I found that the extension still works with the 2 APIs you mentioned.
To easily support this problem for you, please create a new ticket here:
- https://mageplaza.freshdesk.com/support/tickets/new
Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.

**Comment by ahinkle** [comment]
I'm having the same issue, #41

**Comment by Jorggea** [comment]
Este problema se resuelve actualizando la versión del Webhook

**Comment by Jorggea** [comment]
This problem is solved by updating the version of the Webhook
