### ISSUE TITLE
Autoload Error on 'Mageplaza_webhook' due to linux vs windows pathing

### ISSUE THREAD

**Issue by tbreuerAcqua** [mageplaza/magento-2-webhook#4]
I have the following error when trying to run the 
`php bin/magento setup:upgrade`

`php bin/magento setup:static-content:deploy -f`

commands:

![mintty_wb6obiwavb](https://user-images.githubusercontent.com/44898122/53017302-6a6a4480-342e-11e9-8481-3f93c258bcf8.png)

**Comment by thaimageplaza** [comment]
Hi,
To solve your issue, Please remove folder C:\wamp67\www\magento2\app\code\Mageplaza\Webhook and check again.
Thank you!

**Comment by tbreuerAcqua** [comment]
Worked! i had tried deleting the /vendor/ folder, but that caused a critical error becouse it was required on the path, i hadnt thought about deleting the /app/ path issue.
I also had to delete C:\wamp64\www\magento2\generated\code\magento\security\model\resourcemodel due to the following error:

`[37;41mThe directory "C:/wamp64/www/magento2/generated/code/Magento/Security/Mo
del/ResourceModel" cannot be deleted Warning!rmdir(C:/wamp64/www/magento2/genera
ted/code/Magento/Security/Model/ResourceModel): Directory not empty[39;49m`

But after i deleted it manually, it worked fine.
