### ISSUE TITLE
Delete method not work

### ISSUE THREAD

**Issue by ghost** [mageplaza/magento-2-webhook#42]
DELETE method actually launches a request with GET method

we test it with delete product and delete category hooks

**Comment by icychocolate98** [comment]
It works fine for me... How are you doing?

**Comment by vivekMage** [comment]
Delete method Not working.
I tried with method DELETE as well as GET too but delete customer is not working.
Any help would be appreciated.
thanks

**Comment by jaredpetersen** [comment]
My team has run into this issue as well on the 1.2.0 release. Any webhook that we create with the DELETE HTTP method will instead call the endpoint with the GET HTTP method.
