### ISSUE TITLE
Invalid security or form key. Please refresh the page.

### ISSUE THREAD

**Issue by kikaju** [mageplaza/magento-2-webhook#43]
After install this extension to magento 2.4. It doesn't work. How to fix it?

**Comment by Shinichi69** [comment]
Hi @kikaju 

I checked it locally with Magneto 2.4.0.
However, the extension is still working fine.

Please provide me some screenshots and steps to reproduce your problem.

Thanks so much!

**Comment by kikaju** [comment]
I can fix it now by download official extension from mageplaza website. thank you.
