### ISSUE TITLE
Missing item.items documentation

### ISSUE THREAD

**Issue by mattjames-counterpart** [mageplaza/magento-2-webhook#47]
We're trying to pass order information to another system, but can't find any documentation on the properties that are available for products in item.items.  We've gleaned a few from other posts, but would like to see the complete list so that we know what's possible.  Is that somewhere that we've missed?  Could you provide those details?

```
{
items: [
{% for product in item.items %}
  {
sku: "{{ product.sku }}",
product_id: {{ product.product_id }},
price: "{{ product.price }}"
  }, 
{% endfor %}
],
order_id: {{ item.entity_id }},
order_number: {{ item.increment_id }},
shipping: "{{ item.shipping_amount }}"
}
```

**Comment by Shinichi69** [comment]
Hi @mattjames-counterpart 

I’m Shin from Mageplaza and I will support you on this ticket.

Currently, the extension does not support displaying the values that you can get of the items in the order.
However, you can access the backend:
STORES-> Attributes-> Product for knowing which attributes you can value with the attribute code:
- https://prnt.sc/uzjl9a

If you have any questions, please contact me via this ticket.
Thank you!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
