### ISSUE TITLE
Get Telephone from an order

### ISSUE THREAD

**Issue by tiagoleitemachado** [mageplaza/magento-2-webhook#48]
I created a new order webhook, but I can't get the telephone number.
I tried the variables below in the message body:
{{ item.billingAddress.telephone }}
{{ item.billing_address.telephone}}

Thanks in advance for the help.

**Comment by Shinichi69** [comment]
Hi @tiagoleitemachado 

I checked your problem on my local.

Please download and replace this file to follow the path:
[Data.zip](https://github.com/mageplaza/magento-2-webhook/files/5398685/Data.zip)

- Webhook/Helper/Data.php

Then please try again with {{ item.billingAddress.telephone }}

**Comment by tiagoleitemachado** [comment]
Thanks, it worked like a charm!
