### ISSUE TITLE
Webhook firing three times at new order

### ISSUE THREAD

**Issue by tiagoleitemachado** [mageplaza/magento-2-webhook#49]
I created a webhook for new order with pending status and it's firing three times after I created a new order.
I changed the configuration to use cron jobs but the error still happens.
I'm using Magento 2.4.

**Comment by Shinichi69** [comment]
Hi @tiagoleitemachado 

I’m Shin from Mageplaza and I will support you on this issue.

Please provide me some screenshots of your problem.

Thanks so much!

**Comment by tiagoleitemachado** [comment]
![store-configuration](https://user-images.githubusercontent.com/49654476/96800588-13272f00-13dc-11eb-8243-77c228c0bd7e.JPG)
![log2](https://user-images.githubusercontent.com/49654476/96800591-13bfc580-13dc-11eb-90cb-fa6f9c1f8b95.JPG)
![log1](https://user-images.githubusercontent.com/49654476/96800593-14585c00-13dc-11eb-88cd-5442dd006be3.JPG)
![configuration2](https://user-images.githubusercontent.com/49654476/96800594-14585c00-13dc-11eb-8920-a79d09df49d1.JPG)
![configuration1](https://user-images.githubusercontent.com/49654476/96800595-14f0f280-13dc-11eb-9f41-531556767436.JPG)
![whatsapp](https://user-images.githubusercontent.com/49654476/96800599-14f0f280-13dc-11eb-9bea-1f15607796ec.JPG)

**Comment by Shinichi69** [comment]
Hi @tiagoleitemachado 

Thanks for your response.

Regarding your issue, please create a ticket and provide us with your site information on that ticket and I will check your issue.
- https://mageplaza.freshdesk.com/support/tickets/new

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
