### ISSUE TITLE
Single Store Mode

### ISSUE THREAD

**Issue by diyontheweb** [mageplaza/magento-2-webhook#5]
Hi,

In Single Store Mode; the store picker doesn't show up. Subsequently when you go to save a new hook; it fails on line 76 of Mageplaza/Webhook/Controller/Adminhtml/ManageHooks/Save.php

Exception #0 (Exception): Warning: implode(): Invalid arguments passed in line 76 of Mageplaza/Webhook/Controller/Adminhtml/ManageHooks/Save.php

You can reproduce the error by putting the store in single store mode. Stores > Configuration > Single Store Mode > Enable

` 
if (isset($data['store_ids']) && $data['store_ids']) {
    $data['store_ids'] = implode(',', $data['store_ids']);
        }
`

**Comment by thaimageplaza** [comment]
Hi, 
For "Single Store Mode" you can access to the link for more information:
https://docs.magento.com/m2/ce/user_guide/stores/store-mode-single.html

And to solve save.php file issue, Please remove your file with attach file.
These are modified files:
Mageplaza/Webhook/Controller/Adminhtml/ManageHooks/Save.php
Please check again. Thank you!
[Save.zip](https://github.com/mageplaza/magento-2-webhook/files/2913795/Save.zip)

**Comment by diyontheweb** [comment]
Thank you! Is there any chance this will be fixed in the repo so a composer update is available?

**Comment by thaimageplaza** [comment]
Hi,
We will update it as soon as possible.
Please look forward to this. Thank you very much for your feedback.

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.

**Comment by peterjaap** [comment]
Here's a patch to use with `vaimo/composer-packages`;

```
Fix store_ids in single store mode

@link https://github.com/mageplaza/magento-2-webhook/issues/5
@package mageplaza/module-webhook
@level 0


diff --git Controller/Adminhtml/ManageHooks/Save.php Controller/Adminhtml/ManageHooks/Save.php
index e5efe65..209fa3b 100755
--- Controller/Adminhtml/ManageHooks/Save.php
+++ Controller/Adminhtml/ManageHooks/Save.php
@@ -83,7 +83,7 @@ class Save extends AbstractManageHooks
         }
 
         if (isset($data['store_ids']) && $data['store_ids']) {
-            $data['store_ids'] = implode(',', $data['store_ids']);
+            $data['store_ids'] = is_array($data['store_ids'])?implode(',', $data['store_ids']):$data['store_ids'];
         }
 
         $hook->addData($data);

```

**Comment by peterjaap** [comment]
I've done a PR #52
