### ISSUE TITLE
Unsubscribe webhook

### ISSUE THREAD

**Issue by peterjaap** [mageplaza/magento-2-webhook#50]
In #6, a webhook was added for a newsletter subscription. Although this webhook can contain the field `status` (subscribed, or unsubscribed), it does not fire when a customer unsubscribes.

**Comment by Shinichi69** [comment]
Hi @peterjaap 

Currently, the extension only supports fire hook when customers or guests subscribe.
If you want the hook to be fired when unsubscribing, please download and replace this file to follow the path:
- mageplaza/module-webhook/Observer/Subscriber.php

Then please try again.

Thanks so much!
[Subscriber.zip](https://github.com/mageplaza/magento-2-webhook/files/5588297/Subscriber.zip)

**Comment by peterjaap** [comment]
@Shinichi69 thanks, I've created a PR https://github.com/mageplaza/magento-2-webhook/pull/51

**Comment by Shinichi69** [comment]
Hi @peterjaap 

I'm very sorry that this will be custom made to your requirements, so this will not be updated in the public version of the extension.
So you can replace this file only after updating the extension.

Thanks so much!

**Comment by peterjaap** [comment]
@Shinichi69 can you eleborate why you feel this is a custom requirement?

It is an extra feature; you can put the status variable into the payload to cover both cases.

**Comment by Shinichi69** [comment]
Hi @peterjaap 

Thanks for your feedback!

We will look at this and update it to the next versions of the extension if possible.

Thanks so much!

**Comment by peterjaap** [comment]
Another idea (to keep backwards compatibility with what people now expect from this hook) is to add a new hook called "Unsubscribe".

**Comment by Shinichi69** [comment]
Hi @peterjaap 

Yes, we will update this soon on the next versions of the extension.

Again, thanks for your feedback!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.

**Comment by peterjaap** [comment]
@Shinichi69 hi you closed this issue due to no response, but you said you will update this in the next version but haven't yet. So I guess you should re-open this issue or otherwise explain why you won't re-open it.
