### ISSUE TITLE
Do not save new item if store is in single store mode.

### ISSUE THREAD

**Issue by redati** [mageplaza/magento-2-webhook#53]
Reproduction:

Enable single store mode.
Go to Manage Hooks and try to create a new one.

Error: [2020-12-03 17:28:24] main.CRITICAL: Warning: implode (): Invalid arguments passed in /vendor/mageplaza/module-webhook/Controller/Adminhtml/ManageHooks/Save.php on line 86

Solution:

Replace:
`
if (isset ($ data ['store_ids']) && $ data ['store_ids']) {
             $ data ['store_ids'] = implode (',', $ data ['store_ids']);
         }

per
  if (isset ($ data ['store_ids']) && $ data ['store_ids']) {
             $ data ['store_ids'] = is_array ($ data ['store_ids'])? implode (',', $ data ['store_ids']): $ data ['store_ids'];
   }
`

**Comment by Shinichi69** [comment]
Hi @redati 

I’m Shin from Mageplaza and I will support you on this issue.

I checked your problem again.
You can edit the code as you mentioned.
Or more accurately, you can replace the attached Save.php file and try again.

Thanks so much!
[Save.zip](https://github.com/mageplaza/magento-2-webhook/files/5641119/Save.zip)
