### ISSUE TITLE
How to get 'seller id' as variable

### ISSUE THREAD

**Issue by umarfarukm** [mageplaza/magento-2-webhook#55]
Hello,

We are using [Webkul - Marketplace Multi Vendor Module for Magento 2](https://store.webkul.com/magento2-multi-vendor-marketplace.html) & [Magento 2 Marketplace Seller Price Comparison extension](https://store.webkul.com/Magento2-Marketplace-Seller-Price-Comparison.html) to have different sellers and products based on the seller section.

In the Webhook we want to pass the value of seller id for that product they bought. Can you please help us on how to pass the value as variable?

**Comment by Shinichi69** [comment]
Hi @umarfarukm 

I’m Shin from Mageplaza and I will support you on this issue.

Regarding your issue to get information from other 3rd party extensions.
So please create a ticket here for assistance with this issue:
- https://mageplaza.freshdesk.com/support/tickets/new

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
