### ISSUE TITLE
Webhook not firing for bulk product update

### ISSUE THREAD

**Issue by tekbird** [mageplaza/magento-2-webhook#56]
Hello, as I was testing the webhook on a test Magento instance, the product update hook works correctly on single product updates, but fails for bulk updates. Do I need to configure it somewhere?

**Comment by Shinichi69** [comment]
Hi @tekbird 

I’m Shin from Mageplaza and I will support you on this issue.

Please provide me steps to reproduce your problem.
If possible please send me a video of the problem.

Thanks so much!

**Comment by tekbird** [comment]
@Shinichi69 The video shows a normal update triggering webhook while a bulk update not.

https://user-images.githubusercontent.com/678518/102884869-aae3e080-4452-11eb-8e2d-fc18ee2e01d7.mp4

**Comment by Shinichi69** [comment]
Hi @tekbird 

Thanks for your video!

Firstly, I truly apologize for the inconvenience.
Unfortunately, the current version has not supported this function yet. I'm so sorry about that. 
However, I will surely note it to our developer to consider developing it in the future so please look forward to this. 

Thank you very much for your feedback.

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
