### ISSUE TITLE
Product update webhook blank variable{{ item.quantity_and_stock_status }}

### ISSUE THREAD

**Issue by jason-newvision** [mageplaza/magento-2-webhook#57]
I've added the magento-2-webhook package to a brand new new Magento 2.4 installation.

I'm trying to set up a `Product Update` webhook.

Whenever I include the variable `{{ item.quantity_and_stock_status }}` the entire output body is blank.
It appears that this field is causing an issue with the generation of the payload.

Other configurations such as the following work fine:
`{
"sku": "{{ item.sku }}",
"name": "{{ item.name }}"
}`

Does anyone have any suggestions on what could be causing this issue?

**Comment by jason-newvision** [comment]
As an update. The variable `{{ item.category_ids }}` as mentioned in [this issue](https://github.com/mageplaza/magento-2-webhook/issues/6) also causes the entire payload to be blank. That issue went unresolved.

Can anyone offer any assistance on this?

**Comment by Shinichi69** [comment]
Hi @jason-newvision 

I’m Shin from Mageplaza and I will support you on this issue.

To get the variables you mentioned, please use the variables of the following format:
{
	"Stock": {{ item.quantity_and_stock_status.is_in_stock }}
	"CategoryIds": {{ item.category_ids | join: ", "}}
}

Please try again.

Thanks so much!

**Comment by jason-newvision** [comment]
Hi @Shinichi69.
`{{ item.quantity_and_stock_status.is_in_stock }}` correctly returns a `1` or a `0` for `Stock Status` field.
`{{ item.category_ids | join: ", "}}` also seems to be returning the category ids correctly. Thanks for this.

The main reason for my initial posting is that I was trying to find out the stock level of the item when the webhook was fired.
Is there another variable for this? 

Kind regards
Jason

**Comment by Shinichi69** [comment]
Hi @jason-newvision 

I’m not sure that I can understand your issue/question.
So could you please explain your problem in more details/ steps by steps to replicate the problem and send me some screenshots?

I really hope for your cooperation. 
Thank you!

**Comment by jason-newvision** [comment]
Apologies for the confusion.

I need a field which can return the stock level of the item. 
Does such a field exist?

Kind regards
Jason

**Comment by Shinichi69** [comment]
Hi @jason-newvision 

Could you provide me a screenshot of the specific field you want to get from your product?

Thanks so much!

**Comment by jason-newvision** [comment]
Hi @Shinichi69 

I was after the quantity field:
![image](https://user-images.githubusercontent.com/37378233/103343218-81930800-4a83-11eb-9098-4ec5627e5b86.png)

I've since found that it is available here: `{{ item.quantity_and_stock_status.qty }} ` and this is working well!
Thanks for pointing me in the right direction.

Is there any more documentation for the available fields and their usage?

Kind regards
Jason

**Comment by Shinichi69** [comment]
Hi @jason-newvision 

I'm glad you were able to find the variable yourself.
I am very sorry because currently there is no specific documentation for variables other than the list of variables available in the extension.

However, you can contact us if you have any problems with the extension.
We are here to support you!

Thanks so much!

**Comment by jason-newvision** [comment]
Hi @Shinichi69 

Thanks for coming back to me and for helping me get this sorted.

Have a great new year!

Kind regards
Jason
