### ISSUE TITLE
Webhook to execute when a virtual product is ordered successfully

### ISSUE THREAD

**Issue by supportreq** [mageplaza/magento-2-webhook#59]
Is it possible to trigger a webhook when a specific virtual product is ordered successfully?

Alongside, different product can have a different webhook event?

**Comment by Shinichi69** [comment]
Hi @supportreq 

I’m Shin from Mageplaza and I will support you on this issue.

With the current version of the extension, you can only trigger a webhook with all products in the order.
Currently, the extension does not support features for each product in the order.

However, I will surely note it to our developer to consider developing it in the future so please look forward to this. 

Thank you very much for your feedback.

**Comment by Shinichi69** [comment]
Closed due to no response within 7 days.
