### ISSUE TITLE
Post method is not working

### ISSUE THREAD

**Issue by rakeshorbonix** [mageplaza/magento-2-webhook#6]
Hello,

I have created two webhooks for **New Product & Update Product**.

I am trying to get parameters in POST request but in response a blank array is coming.

But when i am sending a static JSON parameters it is working fine, After selecting "Insert Variables" it is not sending any values to the payload url.

1. Static JSON body :  (Working)
    {
  "data":{
	"category_ids" : "test"
	}
}
2. From Insert Variables :  (Not Working)
  {
  "data":{
	"category_ids" : {{ item.category_ids }}
	}
}
Please find the screenshots.

Please correct me if i have missed something
This is the api Url :

 **https://us-central1-shopscope-prod214312.cloudfunctions.net/api/newProductWebHook**

Thanks
![image](https://user-images.githubusercontent.com/42025800/54520879-ba85e980-498f-11e9-9b8b-cf151075d45e.png)

**Comment by thaimageplaza** [comment]
Hi, 
Please try again with the Form below:
{
"data":{
"category_ids" : "{{ item.category_ids }}"
}
}

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.

**Comment by erikwa-usa** [comment]
Hi,

I am also running into this issue.  When I include {{ item.category_ids }} in a New Product & Update Product webhook the request comes through with no content.

If I remove {{ item.category_ids }} from the body the request comes through with content.

I tried the sample body posted on Mar 20 and it resulted in a request with no content.

**Comment by ronalronal** [comment]
any update here?
