### ISSUE TITLE
Extension does not support HTTP 204 response code

### ISSUE THREAD

**Issue by mpchadwick** [mageplaza/magento-2-webhook#60]
If the endpoint configured returns 204 response this module reports as error.

I believe the issue is here:

https://github.com/mageplaza/magento-2-webhook/blob/v4.0.0/Helper/Data.php#L327

There are a number of success HTTP response codes beyond 200 and 201 (see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses)

The `isSuccess` method is probably a better option for determining whether or not there was an error

https://github.com/zendframework/zend-http/blob/master/src/Response.php#L494-L498

**Comment by Shinichi69** [comment]
Hi @mpchadwick 

I’m Shin from Mageplaza and I will support you on this issue.

Thanks for your feedback.
We will update this in the next version of the extension.
You can download and replace this file to solve your problem:
- mageplaza/module-webhook/Helper/Data.php
[Data.zip](https://github.com/mageplaza/magento-2-webhook/files/5800846/Data.zip)

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
