### ISSUE TITLE
Product update not triggering on version 4.0.0

### ISSUE THREAD

**Issue by janiek** [mageplaza/magento-2-webhook#61]
Magento version: Community edition 2.4.0
PHP: 7.3.20
MySQL: 5.7.31

Webhook configuration:
Update Product:

Method: POST
No Authentication
Content Type: application/json
Body: {"skus": "{{ item.sku }}" }
Expected behaviour: When updating a product a webhook event is fired. Log entry is recorded

Current behaviour: When updating a product no webhook events are recorded at endpoint and no log entries are created.

Similar to #12 but fix doesn't work + different version of magento.

**Comment by Shinichi69** [comment]
Hi @janiek 

I’m Shin from Mageplaza and I will support you on this issue.

I rechecked your problem on my local with Magento 2.4.0.
However, the hook is still fired when updating the product.
Can you provide me some screenshots of your hook set up for me to check?

Thanks so much!

**Comment by janiek** [comment]
@Shinichi69 ,

Here our setup of the hook.
![image](https://user-images.githubusercontent.com/8281506/104705246-f4ee7800-5719-11eb-8747-bfb16e8f13f0.png)

What does work though is the new_invoice webhook.

**Comment by janiek** [comment]
Apparenty I had to enable the new_product webhook before the update_product hook triggers. Strange.

**Comment by Shinichi69** [comment]
Hi @janiek 

Looks like the problem is with your API info.
Please retry your API info with POSTMAN to see if it can connect successfully.

Thanks so much!

**Comment by janiek** [comment]
@Shinichi69 

Can you give more information? What do you mean by API info? the settings in the webhook configuration? The webhook url? 

how is it related to enabling new product ? 

This happened on 2 seperate environments. 

kind regards,
Janiek

**Comment by Shinichi69** [comment]
Hi @janiek 

These are your API credentials so you can submit your own information.
The information you enter in the webhook will correspond to the information in POSTMAN.

For example:
The URL payload corresponds to the URL in POSTMAN.

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
