### ISSUE TITLE
M 2.4.1 - Error when Saving hook on single store

### ISSUE THREAD

**Issue by ilevennet** [mageplaza/magento-2-webhook#62]
Hi,
i'm trying to configure a simple hook for Active campaign.
Magento Open Source 2.4.1
Single Store
Module Mageplaza Webhook v4.0.0

Saving single hook have this:

<pre>1 exception(s):
Exception #0 (Exception): Warning: implode(): Invalid arguments passed in /home/cpro/public_html/vendor/mageplaza/module-webhook/Controller/Adminhtml/ManageHooks/Save.php on line 86
Exception #0 (Exception): Warning: implode(): Invalid arguments passed in /home/cpro/public_html/vendor/mageplaza/module-webhook/Controller/Adminhtml/ManageHooks/Save.php on line 86
#1 implode() called at [vendor/mageplaza/module-webhook/Controller/Adminhtml/ManageHooks/Save.php:86]
#2 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#3 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#4 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#5 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#6 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#7 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save\Interceptor->___callPlugins() called at [generated/code/Mageplaza/Webhook/Controller/Adminhtml/ManageHooks/Save/Interceptor.php:23]
#8 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#9 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#10 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#13 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#14 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#15 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save\Interceptor->___callPlugins() called at [generated/code/Mageplaza/Webhook/Controller/Adminhtml/ManageHooks/Save/Interceptor.php:32]
#16 Mageplaza\Webhook\Controller\Adminhtml\ManageHooks\Save\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#17 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#18 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#19 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#20 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#21 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#22 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#23 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#24 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#25 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>

Attached configuration
<img width="1051" alt="Schermata 2021-02-11 alle 01 00 38" src="https://user-images.githubusercontent.com/1394124/107588940-29642f80-6c05-11eb-931f-5aca554429e7.png">

<img width="1605" alt="Schermata 2021-02-11 alle 01 02 16" src="https://user-images.githubusercontent.com/1394124/107588955-3123d400-6c05-11eb-8969-9375bff274c2.png">

**Comment by ilevennet** [comment]
Update: setting Single Store Mode to false the hook has been saved.

I hope can help someone.

**Comment by phutx** [comment]
Hi @ilevennet ,
I'm Onesh from Mageplaza Support Team.

Please help me replace the Save.zip file in the following path:
app/code/Mageplaza/Webhook/Controller/Adminhtml/ManageHooks/Save.php
Via composer:
mageplaza/module-webhook/Controller/Adminhtml/ManageHooks/Save.php
[Save.zip](https://github.com/mageplaza/magento-2-webhook/files/6162278/Save.zip)

Thank you!
