### ISSUE TITLE
Loops and conditions from Liquid

### ISSUE THREAD

**Issue by serjlaw** [mageplaza/magento-2-webhook#63]
Hi.
You have written that you are using the **liquid** templating engine.
But why the operators don't work.

Loop not work:
{% for var in item.data %}
{{ var }}
{% endfor %}

Conditions not work:
{% if item.data.name %}
{{ item.data.name }}
{% endif %}

What am I doing wrong?

**Comment by phutx** [comment]
Hi @serjlaw ,

Let's create hook order and try using this body:
"items": {
    {% for product in item.items %}
      "SKU": {{ product.sku }}
      "ID": {{ product.product_id }}
      "PRICE": {{ product.price }}
    {% endfor %}
  }
