### ISSUE TITLE
Cannot connect to server. Please try again later.

### ISSUE THREAD

**Issue by eg1981** [mageplaza/magento-2-webhook#64]
Hello

On hook item log I see the message:
Cannot connect to server. Please try again later.

What does it means Or What can be the reason for this?

Thank you

![Edit-New-order-comment-hook-System-Emanuel-Hook](https://user-images.githubusercontent.com/65456275/110240468-b07e9c00-7f54-11eb-9794-50567a00828f.jpg)

**Comment by joshuacody** [comment]
You should be able to go to the Webhook Logs at `System -> Webhook -> Logs` and few the error response there. 

This could be caused by a wide range of things and is difficult to determine without the error response

**Comment by phutx** [comment]
Hi @eg1981 ,

I'm Onesh from Mageplaza Support Team.

Please access system > webhook > log > view and have a check on the Response field to figure out the cause.
After that, please let me know which issue it is, so I am able to support you.

Thanks.
