### ISSUE TITLE
Feature request: Filter webhook by custom logic

### ISSUE THREAD

**Issue by amenk** [mageplaza/magento-2-webhook#65]
Is it possible to filter webhook calls by custom logic, for example, push only orders with virtual products to the webhook?

**Comment by phutx** [comment]
Hi @amenk ,

I'm Onesh from Mageplaza Support Team.

Please help me unzip the file attachment and replace it to the following path:
- app/code/Mageplaza/Webhook/Helper/Data.php

Via composer: 
- mageplaza/module-webhook/Helper/Data.php

After that, kindly use the body below:
"items": {
{% for product in item.visibleItems %}
"SKU": {{ product.sku }}
"ID": {{ product.product_id }}
"PRICE": {{ product.price }}
"QTY": {{ product.qty }}
"TAX": {{ product.tax }}
{% endfor %}
}

Thanks you!
[Data.zip](https://github.com/mageplaza/magento-2-webhook/files/6179234/Data.zip)

**Comment by amenk** [comment]
Thanks
