### ISSUE TITLE
Checking if webhook was fired for order

### ISSUE THREAD

**Issue by Kaktus12341** [mageplaza/magento-2-webhook#67]
Is there a way to check if webook was already fired for specific order id?

We have problem with one of our online payment gateways, we think it changes state of the order to the pending and then after payment capture to the processing causing double requests at the same time. It works fine with other payment methods.

We use webhook to call SMS api to send sms and because of that our customers receive 2 messages.

**Comment by phutx** [comment]
Hi @Kaktus12341,

I'm Onesh From Mageplaza Support Team.
I would love to confirm your point before taking further action. Do you mean when customers use that payment method, you want only one request to be sent?

Thanks

**Comment by Kaktus12341** [comment]
Basically yes, our log for the new order when using this payment method looks like this:
ACTION NEW ORDER
User: xxxxx - May 4, 2021, 7:59 am
ID: 9537
ID_STATE: pending
ID_STATUS: pending
-------------------------
User: xxxxx - May 4, 2021, 7:59 am
ID: 9537
Billing address: 19076
Order: 1000009547
-------------------------

The same is for the second stage when invoice is created, there are always two requests sent and our customers get two messages. When we do last stage "ship order" then everything works ok and only one request is sent.

**Comment by phutx** [comment]
Hi @Kaktus12341,

Please help me replace the file [AfterSave.zip](https://github.com/mageplaza/magento-2-webhook/files/6419824/AfterSave.zip) via the path below:
- app/code/Mageplaza/Webhook/Observer/AfterSave.php
Via composer:
- mageplaza/module-webhook/Observer/AfterSave.php

After that, kindly create an invoice with the payment method above.
You should access the path var/log/test.log, capture the screen with the content in that file, and provide it to me.

Thanks

**Comment by Kaktus12341** [comment]
[https://imgur.com/a/916o8v9](url)
The problematic online payment method is PAYU, that's all what was in that log.

**Comment by phutx** [comment]
Hi @Kaktus12341,

Please let me know which hooks you have made? Also, kindly provide me with the image of these hooks' general tabs.

Thanks you.

**Comment by Kaktus12341** [comment]
We made: Order (new order), new invoice, new shipment - new shipment is always fired from our admin panel and sends only one request.
[https://imgur.com/a/g8LDypy](url)

**Comment by phutx** [comment]
Hi @Kaktus12341,

Thank you for your information as it is very helpful for me. However, I cannot replicate the issue from my side. 
To get further support, you should submit a ticket (https://www.mageplaza.com/contact.html). We are here and more than happy to assist you further.
