### ISSUE TITLE
How to get the message text in the log page

### ISSUE THREAD

**Issue by davebra** [mageplaza/magento-2-webhook#68]
Hi Team,

I have a question about the log section, is it possible to have the message returned by the endpoint in the table under the column "message" with what we can actually see in the response? If so, what the endpoint should return?
![Screen Shot 2021-05-20 at 11 36 05 am](https://user-images.githubusercontent.com/8549971/118907554-13cc7780-b963-11eb-8c1b-75232ba38100.png)
![Screen Shot 2021-05-20 at 11 37 29 am](https://user-images.githubusercontent.com/8549971/118907569-17f89500-b963-11eb-98bc-9d30f9abf769.png)

At the moment, our endpoint is configured to return this (AWS ApiGateway+Lambda):
![Screen Shot 2021-05-20 at 12 03 49 pm](https://user-images.githubusercontent.com/8549971/118907762-77ef3b80-b963-11eb-87b1-6a9c4e2098cf.png)

Thanks for this awesome module!

**Comment by phutx** [comment]
Hi @davebra,

For the time being, the message returns the error notifications when sending HTTP requests gets into trouble. https://prnt.sc/135qijh
If the data is sent completely, the status will be "success". The notice as you mention is unavailable at the moment.
