### ISSUE TITLE
possible to receive a webhook?

### ISSUE THREAD

**Issue by f1-outsourcing** [mageplaza/magento-2-webhook#71]
I was wondering if it is possible to receive and process external requests coming to magento. Thus eg. process a request from a payment provider to change the order state from pending to completed?

**Comment by phutx** [comment]
Hi @f1-outsourcing,

Thanks for your interest in the Mageplaza products. Unfortunately, we haven't provided any features like that at the moment. I'm so sorry for that. 
However, I've passed that feedback along to our development team to suggest making it more readily available if possible.
  
Once again, thank you very much for your valuable feedback and significant contribution.
If you have any further questions/issues, please feel welcome to reach back out as we would be more than happy to assist. 

I wish you a great day!

**Comment by f1-outsourcing** [comment]
Very nice !!!
