### ISSUE TITLE
article not correct

### ISSUE THREAD

**Issue by f1-outsourcing** [mageplaza/magento-2-webhook#72]
https://firebearstudio.com/blog/magento-2-webhooks-automation-detailed-guide-top-solutions.html#Webhooks_Explained

 You start your text with:

"Your Magento 2 website, in its turn, incorporates a so-called “listener” – the URL designed to perform two actions. Firstly, it receives a response from the webhooks. Secondly, it performs a predefined action shortly after that."

And then you give examples of only outgoing requests from Magento????? I do not see anything about a listener.

**Comment by phutx** [comment]
Hi @f1-outsourcing,

As you see, the module receives the actions performed from the web after returning an action corresponding to methods like get, post, put...
"Listener" is the reception of actions from the website.

Thanks
