### ISSUE TITLE
how do i get customer addresses as array of objects in webhook request payload

### ISSUE THREAD

**Issue by ravi55mobifyi** [mageplaza/magento-2-webhook#73]
hello, 

I have successfully integrated this extension and i am able to get customer details. I see in add fields section there are fields "shipping address" and "billing address". but i want to get all addresses as an array of objects. can you please help me in this, 

this is webhook payload for customer create and update
{
	"id": {{ item.entity_id }},
	"store_id": {{ item.store_id }},
	"website_id": {{ item.website_id }},
	"name_prefix": "{{ item.prefix }}",
	"first_name": "{{ item.firstname }}",
	"middle_name": "{{ item.middlename }}",
	"last_name": "{{ item.lastname }}",
	"name_suffix": "{{ item.suffix }}",
    "email": "{{ item.email }}",
    "dob": "{{ item.dob }}",
    "gender": "{{ item.gender }}",
    "created_at": "{{ item.created_at }}",
    "updated_at": "{{ item.updated_at }}",
    "default_billing": "{{ item.default_billing }}",
    "default_shipping": "{{ item.default_shipping }}"
}

how do i add all addresses as array objects like
"addresses": [
  {
    "address_id": "",
   "city": ""
  },
  {
    "address_id": "",
   "city": ""
  },
  {
    "address_id": "",
   "city": ""
  }
]

**Comment by phutx** [comment]
Hi @ravi55mobifyi,

Kindly go to the file Helper/Data.php -> function `generateLiquidTemplate()` and help me replace with this function:
`public function generateLiquidTemplate($item, $templateHtml)
    {
        try {
            $template       = new Template;
            $filtersMethods = $this->liquidFilters->getFiltersMethods();

            $template->registerFilter($this->liquidFilters);
            $template->parse($templateHtml, $filtersMethods);

            if ($item instanceof Product) {
                $item->setStockItem(null);
            }

            if ($item instanceof \Magento\Customer\Model\Backend\Customer) {
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $customerObj = $objectManager->create('Magento\Customer\Model\Customer')->getCollection();

                $addresses = [];
                foreach($customerObj as $customerObjdata )
                {
                    $addresses[]    = array(
                                        'addressId' => $customerObjdata->getDefaultShippingAddress()->getId(),
                                        'city'      => $customerObjdata->getDefaultShippingAddress()->getCity()
                                    );

                }

                $item->setData('addresses', $addresses);
            }

            if ($item->getShippingAddress()) {
                $item->setData('shippingAddress', $item->getShippingAddress()->getData());
            }

            if ($item->getBillingAddress()) {
                $item->setData('billingAddress', $item->getBillingAddress());
            }

            return $template->render([
                'item' => $item,
            ]);
        } catch (Exception $e) {
            $this->_logger->critical($e->getMessage());
        }

        return '';
    }`
After that, please use the body below:
```
Addresses: [
{% for addresses in item.addresses %}
address Id: {{ addresses['addressId'] }}
City:	    {{ addresses['city'] }},
{% endfor %}
]
```
Thanks.
