### ISSUE TITLE
Cannot escape the characters

### ISSUE THREAD

**Issue by bbansonf** [mageplaza/magento-2-webhook#75]
This is the Body with liquid escape instruction :
![image](https://user-images.githubusercontent.com/82351544/125044328-323b2d80-e0df-11eb-9bf2-e663f86ca1ef.png)

The characters are not escaped.
![image](https://user-images.githubusercontent.com/82351544/125044406-4717c100-e0df-11eb-866b-8d615e878db0.png)

Based on Playground, it should be like this:
![image](https://user-images.githubusercontent.com/82351544/125044361-3c5d2c00-e0df-11eb-9e11-bb591433c34c.png)

**Comment by phutx** [comment]
Hi @bbansonf,

The string was escaped already but will be displayed visually on the browser like the original string.
![Screenshot_23](https://user-images.githubusercontent.com/72056266/125604869-16953789-7614-451b-bf2c-76db0ef41d32.png)

Thanks!

**Comment by bbansonf** [comment]
True. Looks like the request body is escaped already and shown differently on the Log. Anyway, the ticket can be closed. Thanks for the reply!
