### ISSUE TITLE
Webhook - Shipping and billing address

### ISSUE THREAD

**Issue by ralphdejoode** [mageplaza/magento-2-webhook#76]
I updated the webhook for magento to version 4.1.0 and set-up a webhook for updating the shipping address

![image](https://user-images.githubusercontent.com/69723301/125103943-20f12180-e0dd-11eb-9b71-3da49442b67a.png)

However when i look to the log the variables like postal code etc are not visible

The request body = 
{
  "Long_Address": "30",
  "Select_Row": "1",
  "Postal_Code": " ",
  "City": " ",
  "Country": " ",
  "Address_Line_1": " ",
  "Address_Line_2": " ",
  "Address_Line_3": " ",
  "Address_Line_4": " ",
  "Alpha_Name": "Ralph Havermans - de Joode12",
  "Mailing_Name": "Ralph Havermans - de Joode12"
}

So the postal code is not filled. 

Second issue is that when i update the address record the hook is not triggered. Can you please assist?

**Comment by phutx** [comment]
Hi @ralphdejoode,

Please go to the file Helper/Data and replace the function generateLiquidTemplate() with the one below:

`public function generateLiquidTemplate($item, $templateHtml)
    {
        try {
            $template       = new Template;
            $filtersMethods = $this->liquidFilters->getFiltersMethods();

            $template->registerFilter($this->liquidFilters);
            $template->parse($templateHtml, $filtersMethods);

            if ($item instanceof Product) {
                $item->setStockItem(null);
            }

            if ($item instanceof \Magento\Customer\Model\Backend\Customer) {
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $customerObj = $objectManager->create('Magento\Customer\Model\Customer')->getCollection();
                $shipping = '';
                $billing  = '';
                foreach($customerObj as $customerObjdata )
                {
                    if ($customerObjdata->getDefaultShippingAddress()) {
                        $shipping = $customerObjdata->getDefaultShippingAddress();
                    }
                    if ($customerObjdata->getDefaultShippingAddress()) {
                        $billing = $customerObjdata->getDefaultShippingAddress();
                    }
                }
                $item->setData('shippingAddress', $shipping);
                $item->setData('billingAddress', $billing);
            }
            
            if ($item->getShippingAddress()) {
                $item->setData('shippingAddress', $item->getShippingAddress()->getData());
            }

            if ($item->getBillingAddress()) {
                $item->setData('billingAddress', $item->getBillingAddress());
            }

            return $template->render([
                'item' => $item,
            ]);
        } catch (Exception $e) {
            $this->_logger->critical($e->getMessage());
        }

        return '';
    }`

In terms of the 2nd issue, you should save the change after it is made. So the hook can be activated correctly.

Thanks so much!

**Comment by ralphdejoode** [comment]
Hi @phutx thanks for the update. I just replaced the info in the data.php but it still doesn't work.

**Comment by ralphdejoode** [comment]
{
  "Long_Address": "",
  "Select_Row": "1",
  "Postal_Code": " "
 }

**Comment by ralphdejoode** [comment]
![image](https://user-images.githubusercontent.com/69723301/125287951-de6a5780-e31d-11eb-898d-3ff597ca02ac.png)

**Comment by ralphdejoode** [comment]
See data.php i am using Magento ver. 2.4.2-p1 and webhook Version | 4.1.0

[Data.php.zip](https://github.com/mageplaza/magento-2-webhook/files/6801378/Data.php.zip)

**Comment by phutx** [comment]
Hi @ralphdejoode,

What Hook entity is created with your provided image?

**Comment by ralphdejoode** [comment]
I used update customer. I saw an other issue created #77 the same issue.

**Comment by ralphdejoode** [comment]
It's ID 6
![image](https://user-images.githubusercontent.com/69723301/125407783-7f0e5500-e3ba-11eb-897d-2972c0f35cc6.png)

**Comment by ralphdejoode** [comment]
Just checked when i do an update on the customer on the admin side of the webshop it works. Steps to reproduce

1 - go to the admin panel of the website
2 - Select customer - all customers
3 - Select the customer for update
4 - Update the address information
5 - Update the customer name

Then the address information is updated correctly

**Comment by phutx** [comment]
Hello @ralphdejoode,

try this function:
`public function generateLiquidTemplate($item, $templateHtml)
    {
        try {
            $template       = new Template;
            $filtersMethods = $this->liquidFilters->getFiltersMethods();

            $template->registerFilter($this->liquidFilters);
            $template->parse($templateHtml, $filtersMethods);

            if ($item instanceof Product) {
                $item->setStockItem(null);
            }

            if ($item instanceof \Magento\Customer\Model\Backend\Customer) {
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $customerObj   = $objectManager->create('Magento\Customer\Model\Customer')->getCollection();
                
                foreach($customerObj as $customerObjdata )
                {
                    if ($customerObjdata->getDefaultShippingAddress()) {
                        $shipping = $customerObjdata->getDefaultShippingAddress();
                    }
                    if ($customerObjdata->getDefaultBillingAddress()) {
                        $billing = $customerObjdata->getDefaultBillingAddress();
                    }
                }
                $item->setData('shippingAddress', $shipping);
                $item->setData('billingAddress', $billing);
            }
            if ($item->getShippingAddress()) {
                $item->setData('shippingAddress', $item->getShippingAddress()->getData());
            }

            if ($item->getBillingAddress()) {
                $item->setData('billingAddress', $item->getBillingAddress());
            }

            return $template->render([
                'item' => $item,
            ]);
        } catch (Exception $e) {
            $this->_logger->critical($e->getMessage());
        }

        return '';
    }`

**Comment by ralphdejoode** [comment]
Issue can be closed. Discussion continues under #77
