### ISSUE TITLE
update customer webhook not triggering when customer adds address in website

### ISSUE THREAD

**Issue by ravi55mobifyi** [mageplaza/magento-2-webhook#77]
hi, 
I am using this plugin in my magento store. i ma facing some problem in update customer webhook. 
when customer adds address in web site,  update customer webhook is not triggering. 
if i add address in magento admin and save customer details then webhook triggers,. 
can you please help in this, actually customer update webhook is supposed to trigger if 
1. customer updates address field
2. customer adds new address 
3. customer deletes address
4. customer makes some address as default address

**Comment by ralphdejoode** [comment]
See also issue #76 - I think this is the same issue.

**Comment by ravi55mobifyi** [comment]
hello @ralphdejoode 
i have seen it, how ever in my case I am just using existing customer update webhook which is working fine when I update customer's profile details and address add/edit/delete from admin. 
but this webhook is supposed to work same in web site also. 
One if customers have added 2 addresses but this webhook is not triggering for that event.

**Comment by ralphdejoode** [comment]
Hello @ravi55mobifyi ,

I just checked and saw that when i change the address and the customer info on the admin side the webhook does work. When i do it as a customer it does not work.

**Comment by ravi55mobifyi** [comment]
yes @ralphdejoode 
customer will be using web site for all tasks and webhook is supposed to work with web site too.
we need some solution for thus but I don't know how can I approach to webhook dev team so i posted issue here

**Comment by ralphdejoode** [comment]
@ravi55mobifyi  just made a modification in the data.php in the directory helper.  With this modification the address data is send when you press the save button on the customer.

NOTE: Not when clicking on the save address button - what should be the ultimate goal.
[Data.php.zip](https://github.com/mageplaza/magento-2-webhook/files/6809933/Data.php.zip)

**Comment by phutx** [comment]
Hi @ravi55mobifyi,

Because Magento divides Edit and Save Address as a different event from the Save Customer event, Hook entity update_customer does not get the change that you made with Edit and Save Address at the frontend. 
In the backend, when editing the address you still have to save the customer so it works for both.

Thanks!

**Comment by ravi55mobifyi** [comment]
hi @phutx 

thank you for you explanation. it helped me to understand reason. Can you please suggest me any solution on this as I need webhook to be triggered when customer add/update/deletes address from front end also.

**Comment by ravi55mobifyi** [comment]
> Hi @ravi55mobifyi,
> 
> Because Magento divides Edit and Save Address as a different event from the Save Customer event, Hook entity update_customer does not get the change that you made with Edit and Save Address at the frontend.
> In the backend, when editing the address you still have to save the customer so it works for both.
> 
> Thanks!

@phutx can you please help me with some function/code that can trigger update customer event when address is saved/updated/deleted.

**Comment by phutx** [comment]
Hi @ravi55mobifyi,

What version of the Webhook module are you using?

**Comment by ravi55mobifyi** [comment]
> Hi @ravi55mobifyi,
> 
> What version of the Webhook module are you using?

@phutx I am using webhook Version 4.1.0

please help to get customer update webhook when customer adds address/updates address and deletes address from front end.

**Comment by ralphdejoode** [comment]
We are also using webhook version 4.1.0 and also want the same functionality as @ravi55mobifyi  described 
 please help to get customer update webhook when customer adds address/updates address and deletes address from front end.

I think extra webhooks need to be created - add address - update address - delete address. I really think this functionality is a big added value for the product

**Comment by phutx** [comment]
hi @ravi55mobifyi,

Please download and extract the .zip file. Then help me install this module.[Webhook.zip](https://github.com/mageplaza/magento-2-webhook/files/6821052/Webhook.zip)
The extension is updated a Hook entity as Update Address.
![image](https://user-images.githubusercontent.com/72056266/125744701-f03c3c07-ca34-409a-b4b3-a4c16ffec695.png)

After that, you can use the variables below in the template:
```
{{item.entity_id}}
{{item.increment_id}}
{{item.created_at}}
{{item.updated_at}}
{{item.city}}
{{item.company}}
{{item.country_id}}
{{item.fax}}
{{item.firstname}}
{{item.lastname}}
{{item.middlename}}
{{item.postcode}}
{{item.prefix}}
{{item.region}}
{{item.region_id}}
{{item.street}}
{{item.suffix}}
{{item.telephone}}
{{item.vat_id}}
{{item.region_code}}
{{item.id}}
{{item.store_id}}
```
Thanks!

**Comment by ravi55mobifyi** [comment]
Thanks a lot @phutx for you quick help !!!

**Comment by shailesh-mobifyi** [comment]
@phutx 
we are using bitnami magento and installed mageplaza/module-webhook through composer so it's installed under vendor folder
i have updated zip code which is given by you in that folder still i'm not getting `update address` webhook 

![image](https://user-images.githubusercontent.com/52414898/125777543-7784b9de-df5c-494e-b1b5-91de80cd4db5.png)

**Comment by ralphdejoode** [comment]
After deleting the complete directory of /vendor/magaplaza/module-webhook and upload your zip file it works. Is it also possible to show the customer id? Now its the id for the address but i need to have the customer id

**Comment by phutx** [comment]
Hi @ralphdejoode,

Use this variable:
`{{item.customer_id}}`

**Comment by ravi55mobifyi** [comment]
@phutx thank you. It is working now. However we are not able to get webhook event on address delete. 
can you please help me to get that event too.

**Comment by ralphdejoode** [comment]
@Ph

> Hi @ralphdejoode,
> 
> Use this variable:
> `{{item.customer_id}}`

Works indeed :) thanks!

**Comment by phutx** [comment]
Hi @ravi55mobifyi,

Replace the following files with the path:
- app/code/Mageplaza/Webhook/etc/events.xml [
[events.zip](https://github.com/mageplaza/magento-2-webhook/files/6837786/events.zip)
]
- app/code/Mageplaza/Webhook/Model/Config/Source/HookType.php [
[HookType.zip](https://github.com/mageplaza/magento-2-webhook/files/6837789/HookType.zip)
]

Create the following file under the path:
- app/code/Mageplaza/Webhook/Observer/AddressDelete.php [
[AddressDelete.zip](https://github.com/mageplaza/magento-2-webhook/files/6837793/AddressDelete.zip)
]

The module will be created with an entity delete address hook. Then use variables like Hook entity update address.

Thank you!
