### ISSUE TITLE
Missing authorization bearer

### ISSUE THREAD

**Issue by dearwish** [mageplaza/magento-2-webhook#8]
Hello,

I am trying to use the extension, but my server that will receive the events is protected with `Authorization: Bearer <bearer-token>`.
Can you consider adding it please?

Thank you,
David

**Comment by thaimageplaza** [comment]
Hi David,
You can solve your problem by adding "Authorization: Bearer <bearer-token>" to the header.

Example: https://i.imgur.com/Fi6hFYh.png
Have a nice day!

Eric.

**Comment by dearwish** [comment]
Yes, I tried it, but the result contains another Authorization header with Token:

`curl -H "Authorization: Token token=sfg999666t673t7t82" -H "Content-Type: application/json" -H 'Authorization: Bearer access-token' -d '{"customerId": "{{ item.customer_id }}"}' -X POST 'http://api.test.com:8080/api/cart/{{ item.entity_id }}'`

**Comment by thaimageplaza** [comment]
Hi,
Please check your access-token again. 
You can find more information at the link below:
https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication-token.html

Please check again. Thank you!

**Comment by dearwish** [comment]
I added `access-token` just for example, of course. Just to show you that in addition to `-H 'Authorization: Bearer access-token'` there is another Authorization header:  `-H "Authorization: Token token=sfg999666t673t7t82"`.

Anyway, I think it will not harm.
Thank you
