### ISSUE TITLE
Products with Visibility "Not individual" associated to Configurable Product returning duplicated products

### ISSUE THREAD

**Issue by Bernardino18** [mageplaza/magento-2-webhook#80]
I´m using Magento 2.3

Here´s the gist: https://gist.github.com/Bernardino18/e73826dd3e9bde5b8eb859f3795cafc4

**Use case:**    

Purchase:
- two simple products

- three products with visibility not individual that they are associated to configurable product

**What is happening**: 

The product associated to the configurable are duplicated (invalid_data.json) and when showing the correct products associated (30ml, 80ml, 50ml) are returning the UnitPrice to 0

**What i want**: Not show the configurable product to items body (correct_data.json)

**Liquid template using**: liquid_template.txt

**Comment by phutx** [comment]
Hi @Bernardino18,

to fulfill your request, add a product type check condition in the for loop.
`{% if product.product_type != "configurable" %}`

- https://prnt.sc/1qdlzd0

Thanks!

**Comment by Bernardino18** [comment]
Hi,
Thank you for the quick reply.
This works to hide the duplicated configurable product, but the simple product price ({{ product.price | round: 2 }}) is returning 0.
I tried also {% if product.price != "0" %} but now the product name is getting from configurable product and not from the single product associated.
You can check on gist i mentioned
