### ISSUE TITLE
Schedule cron enabled not loading items from order

### ISSUE THREAD

**Issue by Bernardino18** [mageplaza/magento-2-webhook#81]
When activated cronjob the items from new order returns empty.

Magento Version : 2.3.2
Module version: 1.3.1

Gist showing the outputs and the liquid template using: https://gist.github.com/Bernardino18/7ba5e337a09888bfd5ed11c6034056bf

**Comment by phutx** [comment]
Hi @Bernardino18,

I can not reproduce your issue locally. Please submit a ticket to get better support.
You can contact us here: https://www.mageplaza.com/contact.html
Thank you!
