### ISSUE TITLE
Response when Update product is empty when include category ids and tier price variable

### ISSUE THREAD

**Issue by ronalronal** [mageplaza/magento-2-webhook#82]
I try to test data using {{ item.sku }}{{ item.name }}{{ item.price }}{{ item.status }}{{ item.description }}{{ item.image }}{{ item.visibility }}{{ item.url_key }}{{ item.type }}{{ item.quantity_and_stock_status }}{{ item.category_ids }}

but the response is empty, but when I remove {{ item.category_ids }} from above list, the response works properly
the same with {{ item.tier_price }} and several variable are impacting to empty response

Magento version: 2.3.5-p2
Webhook version: 1.3.1 downloaded from https://dashboard.mageplaza.com/

**Comment by phutx** [comment]
Hi @ronalronal,
Because the two variables you are mentioning are returned to the array, you can use the following template:
`{% for categoryId in item.category_ids %}
  {{ categoryId }}
{% endfor %}`

Thank you!
