### ISSUE TITLE
Order webhook **billing_address_id**  from the sales_order table and **item_id** from the sales_order_item table in the output json.

### ISSUE THREAD

**Issue by Sudhakara06** [mageplaza/magento-2-webhook#83]
Hi,

I need the magento web-hook body configuration for the getting order info json.
I am not getting the **billing_address_id**  from the sales_order table and **item_id** from the sales_order_item table in the output json.
![Screenshot from 2021-09-27 11-40-21](https://user-images.githubusercontent.com/91320352/134853408-ed226872-3f7c-4de6-bc37-2f59f760fc1a.png)

{
 "entity_id": "{{ item.entity_id }}",
 "base_currency_code": "{{ item.base_currency_code }}",
 "billing_address_id": "{{ item.billing_address_id }}",
 "items": [
   {% for product in item.items %}
   {
  "base_original_price": "{{ product.base_original_price }}",
  "base_price": "{{ product.base_price }}",
  "item_id": "{{ product.item_id }}",
  "name": "{{ product.name }}",
  "order_id": "{{ product.order_id }}"
 }
  {% if forloop.last == false %}
            ,
            {% endif %}
            {%endfor%}
 ]
}
Regards
Sudhakar

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.

I noticed that you have created a ticket on Freshdesk regarding this issue. so please follow the ticket you created
[117832](https://mageplaza.freshdesk.com/a/tickets/117832)

**Comment by giaphn** [comment]
closed for no response in 7 days
