### ISSUE TITLE
list of all attributes the plugin handles?

### ISSUE THREAD

**Issue by dmcmillin** [mageplaza/magento-2-webhook#86]
Right now I am trying to find a list of all basic attributes that can be utilized using the item.XXX method as well as customer variables. If I created a variable/attribute for customers called custnetid that can be viewed globally. How would I call it within the webhook system?

Thanks and have a great day!!!

**Comment by phutx** [comment]
Hi @dmcmillin,

In the file Webhook/Helper/Data.php, you can create a new variable in the function generateLiquidTemplate. https://i.imgur.com/FlhiD38.png
For example:
`$item->setData('custnetid', <value>;`
and call in body Liquid template : {{ item.custnetid }}
Thank you!
