### ISSUE TITLE
Adding new webhooks

### ISSUE THREAD

**Issue by dearwish** [mageplaza/magento-2-webhook#9]
Hello,

Can you describe a procedure of adding new webhooks that are currently not available?

For example:
- Create cart
- Update cart
- Delete cart
- Add item to cart
- Change item quantity
- etc.

Thank you,
David

**Comment by thaimageplaza** [comment]
Hi David,
You can find describe a procedure of adding new webhooks in below link:
https://docs.mageplaza.com/webhook/index.html

Please check again. Thank you!
Eric.

**Comment by dearwish** [comment]
Hi, thanks for quick response.

I am looking for a procedure to add new types of Web hooks. Currently the [Add New](https://i.imgur.com/HU9ucq4.png) contains a predefined type of web hooks. I want to add more events to be supported like "Item added to cart".
Is it possible?

**Comment by NgoDuVietHung97** [comment]
Hi @dearwish,

We can add more event like that, but it is very complicated because we have to change so much on the source code. So for now, it is impossible.

However, I will surely note it to our developer to consider developing in the future so please look forward to this.
Thank you!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
