### ISSUE TITLE
How do I get the payment method for an order?

### ISSUE THREAD

**Issue by corpsysgit** [mageplaza/magento-2-webhook#97]
How do I get the payment method for an order?

**Comment by phutx** [comment]
Hi @corpsysgit,

I'm Onesh from Mageplaza.
You can use this variable:
`{{ item.payment.additional_information.method_title }}`

Thank you.

**Comment by corpsysgit** [comment]
Thanks!

**Comment by corpsysgit** [comment]
Not work for new order. New invoice doesn't work either.

**Comment by corpsysgit** [comment]
????
